---
- name: merge variables passed to role and the defaults
  set_fact:
    weed: "{{ default_weed | combine((input | default({})), recursive=True) }}"

- name: check some variables value
  assert:
    that:
      - "action_task in ['install', 'uninstall']"

- name: define seaweed master host if not done
  add_host:
    hostname: "{{ groups['all'][0] }}"
    groups: weed_master
  when: groups['weed_master'] is not defined
  changed_when: False

- name: define seaweed filer host if not done
  add_host:
    hostname: "{{ groups['all'][0] }}"
    groups: weed_filer
  when: groups['weed_filer'] is not defined
  changed_when: False

- name: gather fact from weed masters
  setup:
  delegate_to: "{{ item }}"
  loop: "{{ groups['weed_master'] }}"

- name: gather fact from weed filers
  setup:
  delegate_to: "{{ item }}"
  loop: "{{ groups['weed_filer'] }}"

- name: gather fact from weed mount
  setup:
  delegate_to: "{{ item }}"
  loop: "{{ groups['weed_mount'] }}"

- name: "Run action {{ action_task }}"
  include_tasks: "{{ action_task }}.yml"
